[project]
name = "stamp"
version = "2.0.0-dev0"
authors = [
    { name = "Omar El Nahhas", email = "omar.el_nahhas@tu-dresden.de" },
    { name = "Marko van Treeck", email = "markovantreeck@gmail.com" },
    { name = "Georg Wölflein", email = "georgw7777@gmail.com" },
    { name = "Tim Lenz", email = "tim.lenz@tu-dresden.de" },
    { name = "Laura Žigutytė", email = "laura.zigutyte@tu-dresden.de" },
    { name = "Cornelius Kummer", email = "cornelius.kummer@tu-dresden.de" },
]
description = "A protocol for Solid Tumor Associative Modeling in Pathology"
readme = "README.md"
requires-python = ">=3.10"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "einops>=0.8.0",
    "h5py>=3.12.1",
    "huggingface-hub>=0.26.2",
    "jaxtyping>=0.2.36",
    "lightning>=2.4.0",
    "matplotlib>=3.9.2",
    "opencv-python>=4.10.0.84",
    "openpyxl>=3.1.5",
    "openslide-bin>=4.0.0.6",
    "openslide-python>=1.4.1",
    "packaging>=24.2",
    "pandas>=2.2.3",
    "pydantic>=2.10.3",
    "pyyaml>=6.0.2",
    "scikit-learn>=1.5.2",
    "torch>=2.5.1",
    "torchmetrics>=1.6.0",
    "tqdm>=4.66.6",
]

[project.optional-dependencies]
ctranspath = [
    "gdown>=5.2.0",
    "torchvision>=0.20.1",
]
#uni = [
#    "timm>=0.9.8",
#    "uni",
#]
conch = [
    "conch",
]
dinobloom = [
    "torchvision>=0.20.1",
    "xformers>=0.0.28.post3",
]
virchow2 = [
    "timm>=0.9.11",
]
all = ["stamp[ctranspath,conch,dinobloom,virchow2]"]

[project.scripts]
"stamp" = "stamp.__main__:main"

[project.urls]
"Homepage" = "https://github.com/KatherLab/STAMP"
"Bug Tracker" = "https://github.com/KatherLab/STAMP/issues"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "pyright>=1.1.389",
    "pytest>=8.3.4",
    "ruff>=0.8.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
uni = { git = "https://github.com/mahmoodlab/UNI.git", rev = "f8f32c60a1d86805fdcb7317673c45318dac4806" }
conch = { git = "https://github.com/Mahmoodlab/CONCH.git", rev = "02d6ac59cc20874bff0f581de258c2b257f69a84" }
